#!/usr/bin/env bash
DEV_ENV="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
dry_run="0"

if [ -z "$XDG_CONFIG_HOME" ]; then
    echo "no xdg config home"
    echo "using ~/.config"
    XDG_CONFIG_HOME=$HOME/.config
fi

if [[ $1 == "--dry" ]]; then
    dry_run="1"
fi

log() {
    if [[ $dry_run == "1" ]]; then
        echo "[DRY_RUN]: $1"
    else
        echo "$1"
    fi
}

log "env: $DEV_ENV"

symlink() {
    log "removing symlink for: $2"
    if [[ $dry_run == "0" ]]; then
        rm $2
    fi
    log "create symlink: $1 to $2"
    if [[ $dry_run == "0" ]]; then
        ln -s $1 $2
    fi
}

symlink $DEV_ENV/env/.tmux.conf ~/.tmux.conf
symlink $DEV_ENV/env/.zshrc ~/.zshrc
symlink $DEV_ENV/env/.gdbinit ~/.gdbinit
symlink $DEV_ENV/ext/tmux-sessionizer/tmux-sessionizer $HOME/.tmux-sessionizer
symlink $DEV_ENV/env/.config/nvim $XDG_CONFIG_HOME/nvim
symlink $DEV_ENV/.local/scripts ~/.local

