#!/usr/bin/env bash

git config --global user.email "mateus.alves.unb@gmail.com"
git config --global user.name "Mateus Alves"

# luarocks
pushd /tmp/luarocks-3.11.1
(
    wget --output-document /tmp/luarocks.tar.gz https://luarocks.org/releases/luarocks-3.11.1.tar.gz
    tar zxpf /tmp/luarocks.tar.gz -C /tmp
    cd
    ./configure && make && sudo make install
)
popd

sudo luarocks install luacheck
